# Generated by Django 4.2.6 on 2024-01-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbtshop', '0002_sbtproduct_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='info',
            field=models.TextField(blank=True),
        ),
    ]
