# Generated by Django 4.2.6 on 2023-11-29 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_createprojects_galeriacreateprojectitbusiness_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galeriacreateitbusiness',
            name='image_10',
        ),
        migrations.RemoveField(
            model_name='galeriacreateitbusiness',
            name='image_11',
        ),
        migrations.RemoveField(
            model_name='galeriacreateitbusiness',
            name='image_12',
        ),
        migrations.RemoveField(
            model_name='galeriacreateitbusiness',
            name='image_13',
        ),
        migrations.RemoveField(
            model_name='galeriacreateitbusiness',
            name='image_14',
        ),
        migrations.RemoveField(
            model_name='galeriacreateitbusiness',
            name='image_15',
        ),
        migrations.RemoveField(
            model_name='galeriacreateitbusiness',
            name='image_16',
        ),
        migrations.RemoveField(
            model_name='galeriacreateitbusiness',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='galeriacreateitbusiness',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='galeriacreateitbusiness',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='galeriacreateitbusiness',
            name='image_5',
        ),
        migrations.RemoveField(
            model_name='galeriacreateitbusiness',
            name='image_6',
        ),
        migrations.RemoveField(
            model_name='galeriacreateitbusiness',
            name='image_7',
        ),
        migrations.RemoveField(
            model_name='galeriacreateitbusiness',
            name='image_8',
        ),
        migrations.RemoveField(
            model_name='galeriacreateitbusiness',
            name='image_9',
        ),
    ]
