# Generated by Django 4.2.6 on 2023-12-30 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_commingsoon_home_titulo_commingsoonform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createitbusiness',
            name='numero_coffe',
        ),
        migrations.RemoveField(
            model_name='createitbusiness',
            name='numero_experiencia',
        ),
        migrations.RemoveField(
            model_name='createitbusiness',
            name='numero_horas',
        ),
        migrations.RemoveField(
            model_name='createitbusiness',
            name='numero_wins',
        ),
    ]
