# Generated by Django 4.2.6 on 2024-01-03 18:32

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('webapp', '0010_remove_createitbusiness_ts_info1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='TS_info1',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='TS_info2',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='TS_info3',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='TS_info4',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='TS_info5',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='TS_info6',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='banner_title',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='banner_title10',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='banner_title4',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='banner_title5',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='banner_title6',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='banner_title7',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='banner_title8',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='banner_title9',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='custom_title',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='info1',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='info2',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='info3',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='info4',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='info5',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='info6',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='info7',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='info8',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='info9',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='numero_coffe',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='numero_experiencia',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='numero_horas',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='numero_wins',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='product_1',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='product_2',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='product_3',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='product_4',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='product_5',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='product_6',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='product_description_1',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='product_description_2',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='product_description_3',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='product_description_4',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='product_description_5',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='product_description_6',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='slogan',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='slogan_descriptcion',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='team_1',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='team_2',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='team_3',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='team_4',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='team_descrp_1',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='team_descrp_2',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='team_descrp_3',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='team_descrp_4',
        ),
        migrations.RemoveField(
            model_name='galeriacontactus',
            name='image_10',
        ),
        migrations.RemoveField(
            model_name='galeriacontactus',
            name='image_11',
        ),
        migrations.RemoveField(
            model_name='galeriacontactus',
            name='image_12',
        ),
        migrations.RemoveField(
            model_name='galeriacontactus',
            name='image_13',
        ),
        migrations.RemoveField(
            model_name='galeriacontactus',
            name='image_14',
        ),
        migrations.RemoveField(
            model_name='galeriacontactus',
            name='image_15',
        ),
        migrations.RemoveField(
            model_name='galeriacontactus',
            name='image_16',
        ),
        migrations.RemoveField(
            model_name='galeriacontactus',
            name='image_17',
        ),
        migrations.RemoveField(
            model_name='galeriacontactus',
            name='image_18',
        ),
        migrations.RemoveField(
            model_name='galeriacontactus',
            name='image_19',
        ),
        migrations.RemoveField(
            model_name='galeriacontactus',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='galeriacontactus',
            name='image_20',
        ),
        migrations.RemoveField(
            model_name='galeriacontactus',
            name='image_21',
        ),
        migrations.RemoveField(
            model_name='galeriacontactus',
            name='image_22',
        ),
        migrations.RemoveField(
            model_name='galeriacontactus',
            name='image_23',
        ),
        migrations.RemoveField(
            model_name='galeriacontactus',
            name='image_24',
        ),
        migrations.RemoveField(
            model_name='galeriacontactus',
            name='image_25',
        ),
        migrations.RemoveField(
            model_name='galeriacontactus',
            name='image_26',
        ),
        migrations.RemoveField(
            model_name='galeriacontactus',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='galeriacontactus',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='galeriacontactus',
            name='image_5',
        ),
        migrations.RemoveField(
            model_name='galeriacontactus',
            name='image_6',
        ),
        migrations.RemoveField(
            model_name='galeriacontactus',
            name='image_7',
        ),
        migrations.RemoveField(
            model_name='galeriacontactus',
            name='image_8',
        ),
        migrations.RemoveField(
            model_name='galeriacontactus',
            name='image_9',
        ),
        migrations.RemoveField(
            model_name='galeriacontactus',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='galeriacontactus',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='createitbusiness',
            name='TS_info1',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Subtitulo info'),
        ),
        migrations.AddField(
            model_name='createitbusiness',
            name='TS_info2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Subtitulo-2 info'),
        ),
        migrations.AddField(
            model_name='createitbusiness',
            name='TS_info3',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Subtitulo-3 info'),
        ),
        migrations.AddField(
            model_name='createitbusiness',
            name='TS_info4',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Subtitulot-4 info'),
        ),
        migrations.AddField(
            model_name='createitbusiness',
            name='TS_info5',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Subtitulo-5 info'),
        ),
        migrations.AddField(
            model_name='createitbusiness',
            name='TS_info6',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Subtitulo-6 info'),
        ),
        migrations.AddField(
            model_name='createitbusiness',
            name='banner_title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Call Action Title'),
        ),
        migrations.AddField(
            model_name='createitbusiness',
            name='banner_title10',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='we improve'),
        ),
        migrations.AddField(
            model_name='createitbusiness',
            name='banner_title4',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Titulo de galeria-1 '),
        ),
        migrations.AddField(
            model_name='createitbusiness',
            name='banner_title5',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Titulo de galeria-2  '),
        ),
        migrations.AddField(
            model_name='createitbusiness',
            name='banner_title6',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Titulo de galeria-3  '),
        ),
        migrations.AddField(
            model_name='createitbusiness',
            name='banner_title7',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Titulo de galeria-4  '),
        ),
        migrations.AddField(
            model_name='createitbusiness',
            name='banner_title8',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Titulo de galeria-5  '),
        ),
        migrations.AddField(
            model_name='createitbusiness',
            name='banner_title9',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Titulo de galeria-6  '),
        ),
        migrations.AddField(
            model_name='createitbusiness',
            name='info1',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='info'),
        ),
        migrations.AddField(
            model_name='createitbusiness',
            name='info2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='info-2'),
        ),
        migrations.AddField(
            model_name='createitbusiness',
            name='info3',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='info-3'),
        ),
        migrations.AddField(
            model_name='createitbusiness',
            name='info4',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='info-4'),
        ),
        migrations.AddField(
            model_name='createitbusiness',
            name='info5',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='info-5'),
        ),
        migrations.AddField(
            model_name='createitbusiness',
            name='info6',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='info-6'),
        ),
        migrations.AddField(
            model_name='createitbusiness',
            name='info7',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='IT business analytics'),
        ),
        migrations.AddField(
            model_name='createitbusiness',
            name='info8',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='IT business cloud DevOps'),
        ),
        migrations.AddField(
            model_name='createitbusiness',
            name='info9',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='IT business Media'),
        ),
        migrations.AddField(
            model_name='createitbusiness',
            name='product_1',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Product-1'),
        ),
        migrations.AddField(
            model_name='createitbusiness',
            name='product_2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Product-2'),
        ),
        migrations.AddField(
            model_name='createitbusiness',
            name='product_3',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Product-3'),
        ),
        migrations.AddField(
            model_name='createitbusiness',
            name='product_4',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Product-4'),
        ),
        migrations.AddField(
            model_name='createitbusiness',
            name='product_5',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Product-5'),
        ),
        migrations.AddField(
            model_name='createitbusiness',
            name='product_6',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Product-6'),
        ),
        migrations.AddField(
            model_name='createitbusiness',
            name='product_description_1',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripcion Product-1'),
        ),
        migrations.AddField(
            model_name='createitbusiness',
            name='product_description_2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripcion Product-2'),
        ),
        migrations.AddField(
            model_name='createitbusiness',
            name='product_description_3',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripcion Product-3'),
        ),
        migrations.AddField(
            model_name='createitbusiness',
            name='product_description_4',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripcion Product-4'),
        ),
        migrations.AddField(
            model_name='createitbusiness',
            name='product_description_5',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripcion Product-5'),
        ),
        migrations.AddField(
            model_name='createitbusiness',
            name='product_description_6',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripcion Product-6'),
        ),
        migrations.AddField(
            model_name='createitbusiness',
            name='slogan',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='slogan'),
        ),
        migrations.AddField(
            model_name='createitbusiness',
            name='slogan_descriptcion',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='slogan Description'),
        ),
        migrations.AddField(
            model_name='createitbusiness',
            name='team_1',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='team-1'),
        ),
        migrations.AddField(
            model_name='createitbusiness',
            name='team_2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='team-2'),
        ),
        migrations.AddField(
            model_name='createitbusiness',
            name='team_3',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='team-3'),
        ),
        migrations.AddField(
            model_name='createitbusiness',
            name='team_4',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='team-4'),
        ),
        migrations.AddField(
            model_name='createitbusiness',
            name='team_descrp_1',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='team descripcion-1'),
        ),
        migrations.AddField(
            model_name='createitbusiness',
            name='team_descrp_2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='team descripcion-2'),
        ),
        migrations.AddField(
            model_name='createitbusiness',
            name='team_descrp_3',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='team descripcion-3'),
        ),
        migrations.AddField(
            model_name='createitbusiness',
            name='team_descrp_4',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='team descripcion-4'),
        ),
        migrations.AddField(
            model_name='galeriacreateitbusiness',
            name='image_17',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='logo_parther'),
        ),
        migrations.AddField(
            model_name='galeriacreateitbusiness',
            name='image_18',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='logo_parther'),
        ),
        migrations.AddField(
            model_name='galeriacreateitbusiness',
            name='image_19',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='logo_parther'),
        ),
        migrations.AddField(
            model_name='galeriacreateitbusiness',
            name='image_20',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='logo_parther'),
        ),
        migrations.AddField(
            model_name='galeriacreateitbusiness',
            name='image_21',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='logo_parther'),
        ),
        migrations.AddField(
            model_name='galeriacreateitbusiness',
            name='image_22',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='logo_parther'),
        ),
        migrations.AddField(
            model_name='galeriacreateitbusiness',
            name='image_23',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='logo_parther'),
        ),
        migrations.AddField(
            model_name='galeriacreateitbusiness',
            name='image_24',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='logo_parther'),
        ),
        migrations.AddField(
            model_name='galeriacreateitbusiness',
            name='image_25',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='logo_parther'),
        ),
        migrations.AddField(
            model_name='galeriacreateitbusiness',
            name='image_26',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='logo_parther'),
        ),
        migrations.AddField(
            model_name='galeriacreateitbusiness',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logotipo SmartQuail'),
        ),
        migrations.AddField(
            model_name='galeriacreateitbusiness',
            name='profile_pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(blank=True, help_text='Reescribe el  Titulo de la publicacion ', max_length=100, null=True),
        ),
    ]
