# Generated by Django 4.2.6 on 2024-01-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_remove_contactus_ts_info1_remove_contactus_ts_info2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='custom_title',
            field=models.CharField(blank=True, help_text='Reescribe el  Titulo de la publicacion ', max_length=100, null=True),
        ),
    ]
