# Generated by Django 4.2.6 on 2024-01-03 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_contactus_custom_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='galeriacontactus',
            name='image',
        ),
        migrations.RemoveField(
            model_name='galeriacontactus',
            name='page',
        ),
        migrations.DeleteModel(
            name='consultascontact',
        ),
        migrations.DeleteModel(
            name='contactus',
        ),
        migrations.DeleteModel(
            name='GaleriaContactus',
        ),
    ]
