# Generated by Django 4.2.6 on 2024-01-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sblshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sblproduct',
            name='conditions',
            field=models.TextField(blank=True),
        ),
    ]
